// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
	"reflect"
	"testing"

	"github.com/jotaro-ethers/soundcloud/utils"
)


func TestQueries_CreateAccount(t *testing.T) {
	var accountParams CreateAccountParams = CreateAccountParams{
		Username: utils.RandomString(20),
		DisplayName: sql.NullString{ String: utils.RandomString(20), Valid: true},
		Email: utils.RandomString(20)+"@gmail.com",
		Password: utils.RandomString(20),
		Bio: sql.NullString{ String: utils.RandomString(20), Valid: true},
		AvatarUrl: sql.NullString{ String: utils.RandomString(20), Valid: true},
	}
	type fields struct {
		db                              DBTX
		tx                              *sql.Tx
		addListenHistoryStmt            *sql.Stmt
		addSongToPlaylistStmt           *sql.Stmt
		cancelSubscriptionStmt          *sql.Stmt
		createAccountStmt               *sql.Stmt
		createCommentStmt               *sql.Stmt
		createPlaylistStmt              *sql.Stmt
		createReportStmt                *sql.Stmt
		createSongStmt                  *sql.Stmt
		createSubscriptionStmt          *sql.Stmt
		deleteAccountStmt               *sql.Stmt
		deleteCommentStmt               *sql.Stmt
		deletePlaylistStmt              *sql.Stmt
		deleteReportStmt                *sql.Stmt
		deleteRepostStmt                *sql.Stmt
		deleteSongStmt                  *sql.Stmt
		followUserStmt                  *sql.Stmt
		getAccountByIdStmt              *sql.Stmt
		getAllAccountsStmt              *sql.Stmt
		getAllPlaylistsStmt             *sql.Stmt
		getAllSongsStmt                 *sql.Stmt
		getCommentsBySongIdStmt         *sql.Stmt
		getFollowersStmt                *sql.Stmt
		getFollowingStmt                *sql.Stmt
		getLikesBySongIdStmt            *sql.Stmt
		getListenHistoryByAccountIdStmt *sql.Stmt
		getPlaylistByIdStmt             *sql.Stmt
		getReportsByAccountIdStmt       *sql.Stmt
		getReportsBySongIdStmt          *sql.Stmt
		getRepostsByAccountIdStmt       *sql.Stmt
		getRepostsBySongIdStmt          *sql.Stmt
		getSongByIdStmt                 *sql.Stmt
		getSongsByPlaylistIdStmt        *sql.Stmt
		getSubscriptionsByAccountIdStmt *sql.Stmt
		likeSongStmt                    *sql.Stmt
		removeSongFromPlaylistStmt      *sql.Stmt
		repostSongStmt                  *sql.Stmt
		unfollowUserStmt                *sql.Stmt
		unlikeSongStmt                  *sql.Stmt
		updateAccountStmt               *sql.Stmt
		updatePlaylistStmt              *sql.Stmt
		updateSongStmt                  *sql.Stmt
	}
	type args struct {
		ctx context.Context
		arg CreateAccountParams
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    Account
		wantErr bool
	}{
		{
			name :"CreateAccount OK",
			args: args{
				ctx: context.TODO(),
				arg: accountParams,
			},
			want: Account{
				Username: accountParams.Username,
				DisplayName: accountParams.DisplayName,
				Email: accountParams.Email,
				Password: accountParams.Password,
				Bio: accountParams.Bio,
				AvatarUrl: accountParams.AvatarUrl,
				IsVerified: false,
				Role: "user",
			},
			wantErr: false,
		},	
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			q := &Queries{
				db:                              tt.fields.db,
				tx:                              tt.fields.tx,
				addListenHistoryStmt:            tt.fields.addListenHistoryStmt,
				addSongToPlaylistStmt:           tt.fields.addSongToPlaylistStmt,
				cancelSubscriptionStmt:          tt.fields.cancelSubscriptionStmt,
				createAccountStmt:               tt.fields.createAccountStmt,
				createCommentStmt:               tt.fields.createCommentStmt,
				createPlaylistStmt:              tt.fields.createPlaylistStmt,
				createReportStmt:                tt.fields.createReportStmt,
				createSongStmt:                  tt.fields.createSongStmt,
				createSubscriptionStmt:          tt.fields.createSubscriptionStmt,
				deleteAccountStmt:               tt.fields.deleteAccountStmt,
				deleteCommentStmt:               tt.fields.deleteCommentStmt,
				deletePlaylistStmt:              tt.fields.deletePlaylistStmt,
				deleteReportStmt:                tt.fields.deleteReportStmt,
				deleteRepostStmt:                tt.fields.deleteRepostStmt,
				deleteSongStmt:                  tt.fields.deleteSongStmt,
				followUserStmt:                  tt.fields.followUserStmt,
				getAccountByIdStmt:              tt.fields.getAccountByIdStmt,
				getAllAccountsStmt:              tt.fields.getAllAccountsStmt,
				getAllPlaylistsStmt:             tt.fields.getAllPlaylistsStmt,
				getAllSongsStmt:                 tt.fields.getAllSongsStmt,
				getCommentsBySongIdStmt:         tt.fields.getCommentsBySongIdStmt,
				getFollowersStmt:                tt.fields.getFollowersStmt,
				getFollowingStmt:                tt.fields.getFollowingStmt,
				getLikesBySongIdStmt:            tt.fields.getLikesBySongIdStmt,
				getListenHistoryByAccountIdStmt: tt.fields.getListenHistoryByAccountIdStmt,
				getPlaylistByIdStmt:             tt.fields.getPlaylistByIdStmt,
				getReportsByAccountIdStmt:       tt.fields.getReportsByAccountIdStmt,
				getReportsBySongIdStmt:          tt.fields.getReportsBySongIdStmt,
				getRepostsByAccountIdStmt:       tt.fields.getRepostsByAccountIdStmt,
				getRepostsBySongIdStmt:          tt.fields.getRepostsBySongIdStmt,
				getSongByIdStmt:                 tt.fields.getSongByIdStmt,
				getSongsByPlaylistIdStmt:        tt.fields.getSongsByPlaylistIdStmt,
				getSubscriptionsByAccountIdStmt: tt.fields.getSubscriptionsByAccountIdStmt,
				likeSongStmt:                    tt.fields.likeSongStmt,
				removeSongFromPlaylistStmt:      tt.fields.removeSongFromPlaylistStmt,
				repostSongStmt:                  tt.fields.repostSongStmt,
				unfollowUserStmt:                tt.fields.unfollowUserStmt,
				unlikeSongStmt:                  tt.fields.unlikeSongStmt,
				updateAccountStmt:               tt.fields.updateAccountStmt,
				updatePlaylistStmt:              tt.fields.updatePlaylistStmt,
				updateSongStmt:                  tt.fields.updateSongStmt,
			}
			got, err := q.CreateAccount(tt.args.ctx, tt.args.arg)
			if (err != nil) != tt.wantErr {
				t.Errorf("Queries.CreateAccount() error = %v, wantErr %v", err, tt.wantErr)
			}
			tt.want.AccountID = got.AccountID
			tt.want.CreatedAt = got.CreatedAt
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("Queries.CreateAccount() = %v, want %v", got, tt.want)
			}
		})
	}
}
