// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	AccountID int32          `json:"account_id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Comment struct {
	CommentID int32          `json:"comment_id"`
	AccountID sql.NullInt32  `json:"account_id"`
	SongID    sql.NullInt32  `json:"song_id"`
	Content   sql.NullString `json:"content"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Follow struct {
	FollowerID  int32        `json:"follower_id"`
	FollowingID int32        `json:"following_id"`
	FollowedAt  sql.NullTime `json:"followed_at"`
}

type Like struct {
	AccountID int32        `json:"account_id"`
	SongID    int32        `json:"song_id"`
	LikedAt   sql.NullTime `json:"liked_at"`
}

type ListenHistory struct {
	AccountID  int32        `json:"account_id"`
	SongID     int32        `json:"song_id"`
	ListenedAt sql.NullTime `json:"listened_at"`
}

type Playlist struct {
	PlaylistID int32         `json:"playlist_id"`
	Name       string        `json:"name"`
	AccountID  sql.NullInt32 `json:"account_id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type PlaylistSong struct {
	PlaylistID int32        `json:"playlist_id"`
	SongID     int32        `json:"song_id"`
	AddedAt    sql.NullTime `json:"added_at"`
}

type Report struct {
	ReportID   int32          `json:"report_id"`
	AccountID  sql.NullInt32  `json:"account_id"`
	SongID     sql.NullInt32  `json:"song_id"`
	Reason     sql.NullString `json:"reason"`
	ReportedAt sql.NullTime   `json:"reported_at"`
}

type Song struct {
	SongID     int32          `json:"song_id"`
	Title      string         `json:"title"`
	Duration   time.Time      `json:"duration"`
	FileUrl    string         `json:"file_url"`
	AccountID  sql.NullInt32  `json:"account_id"`
	Genre      sql.NullString `json:"genre"`
	UploadDate sql.NullTime   `json:"upload_date"`
	PlayCount  sql.NullInt32  `json:"play_count"`
	LikeCount  sql.NullInt32  `json:"like_count"`
}

type Subscription struct {
	SubscriptionID int32          `json:"subscription_id"`
	AccountID      sql.NullInt32  `json:"account_id"`
	PlanType       sql.NullString `json:"plan_type"`
	StartDate      sql.NullTime   `json:"start_date"`
	EndDate        sql.NullTime   `json:"end_date"`
}
