// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: playlist.sql

package db

import (
	"context"
	"database/sql"
)

const createPlaylist = `-- name: CreatePlaylist :exec
INSERT INTO Playlist (name, account_id)
VALUES ($1, $2)
`

type CreatePlaylistParams struct {
	Name      string        `json:"name"`
	AccountID sql.NullInt32 `json:"account_id"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) error {
	_, err := q.exec(ctx, q.createPlaylistStmt, createPlaylist, arg.Name, arg.AccountID)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM Playlist WHERE playlist_id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, playlistID int32) error {
	_, err := q.exec(ctx, q.deletePlaylistStmt, deletePlaylist, playlistID)
	return err
}

const getPlaylistById = `-- name: GetPlaylistById :one
SELECT playlist_id, name, account_id, created_at FROM Playlist WHERE playlist_id = $1
`

func (q *Queries) GetPlaylistById(ctx context.Context, playlistID int32) (Playlist, error) {
	row := q.queryRow(ctx, q.getPlaylistByIdStmt, getPlaylistById, playlistID)
	var i Playlist
	err := row.Scan(
		&i.PlaylistID,
		&i.Name,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE Playlist
SET name = $1
WHERE playlist_id = $2
`

type UpdatePlaylistParams struct {
	Name       string `json:"name"`
	PlaylistID int32  `json:"playlist_id"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.exec(ctx, q.updatePlaylistStmt, updatePlaylist, arg.Name, arg.PlaylistID)
	return err
}
