// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error
	AddToListenHistory(ctx context.Context, arg AddToListenHistoryParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) error
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) error
	CreateReport(ctx context.Context, arg CreateReportParams) error
	CreateSong(ctx context.Context, arg CreateSongParams) error
	DeleteAccount(ctx context.Context, accountID int32) error
	DeleteComment(ctx context.Context, commentID int32) error
	DeletePlaylist(ctx context.Context, playlistID int32) error
	DeleteReport(ctx context.Context, reportID int32) error
	DeleteSong(ctx context.Context, songID int32) error
	FollowAccount(ctx context.Context, arg FollowAccountParams) error
	GetAccountById(ctx context.Context, accountID int32) (Account, error)
	GetCommentsBySongId(ctx context.Context, songID sql.NullInt32) ([]Comment, error)
	GetFollowers(ctx context.Context, followingID int32) ([]Follow, error)
	GetFollowing(ctx context.Context, followerID int32) ([]Follow, error)
	GetLikesBySongId(ctx context.Context, songID int32) ([]Like, error)
	GetListenHistoryByAccountId(ctx context.Context, accountID int32) ([]ListenHistory, error)
	GetPlaylistById(ctx context.Context, playlistID int32) (Playlist, error)
	GetPlaylistSongs(ctx context.Context, playlistID int32) ([]PlaylistSong, error)
	GetReportsBySongId(ctx context.Context, songID sql.NullInt32) ([]Report, error)
	GetSongById(ctx context.Context, songID int32) (Song, error)
	LikeSong(ctx context.Context, arg LikeSongParams) error
	RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error
	UnfollowAccount(ctx context.Context, arg UnfollowAccountParams) error
	UnlikeSong(ctx context.Context, arg UnlikeSongParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error
	UpdateSong(ctx context.Context, arg UpdateSongParams) error
}

var _ Querier = (*Queries)(nil)
