// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: report.sql

package db

import (
	"context"
	"database/sql"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO Report (account_id, song_id, reason)
VALUES ($1, $2, $3)
`

type CreateReportParams struct {
	AccountID sql.NullInt32  `json:"account_id"`
	SongID    sql.NullInt32  `json:"song_id"`
	Reason    sql.NullString `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.exec(ctx, q.createReportStmt, createReport, arg.AccountID, arg.SongID, arg.Reason)
	return err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM Report WHERE report_id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, reportID int32) error {
	_, err := q.exec(ctx, q.deleteReportStmt, deleteReport, reportID)
	return err
}

const getReportsBySongId = `-- name: GetReportsBySongId :many
SELECT report_id, account_id, song_id, reason, reported_at FROM Report WHERE song_id = $1
`

func (q *Queries) GetReportsBySongId(ctx context.Context, songID sql.NullInt32) ([]Report, error) {
	rows, err := q.query(ctx, q.getReportsBySongIdStmt, getReportsBySongId, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ReportID,
			&i.AccountID,
			&i.SongID,
			&i.Reason,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
